### ISSUE TITLE
Create Docs Page

### ISSUE THREAD

**Issue by Marius9595** [lean-mind/monads#19]
We have to make it public, the repository, to allow contributions

**Comment by Sstark97** [comment]
I've seen a really cool tool for creating documentation, it's called [Starlight](https://starlight.astro.build/es/). It's a very customizable Astro template that the Astro people are using for their own documentation. It could be cool to make a website with this tool 🤩

**Comment by Marius9595** [comment]
Yep! It is cool. Actually, we have a repo (currently private) to create the docs with that: https://github.com/lean-mind/monads-docs :D

**Comment by Marius9595** [comment]
@myugen  and @letorguez  were talking about to deploy this into Github Pages. This is a guide to do it :D https://docs.astro.build/en/guides/deploy/github/
