### ISSUE TITLE
[FEATURE] Add jsdocs

### ISSUE THREAD

**Issue by Marius9595** [lean-mind/monads#39]
### Why do we need this improvement?

To improve the developer experience for users, we need to add code documentation.

### How will this change help?

It makes easier to understand the usage of the API without any consulting of docs

### How could it be implemented/designed?

Adding [jsdocs](https://jsdoc.app/tags-example) in each artifact with API. 

Required for each monad:
- [ ] Description 
- [ ] Usage
- [ ] Example

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/lean-mind/monads/blob/main/docs/CONTRIBUTING.md)

### Are you willing to work on this issue?

No, someone else can work on it.

**Comment by raspberri05** [comment]
Hi, I am an open source contributor and would love to work on this issue

**Comment by raspberri05** [comment]
created a pr: https://github.com/lean-mind/monads/pull/40

(I havent added descriptions in the doc comments yet, so either I or someone else can do that)

**Comment by Marius9595** [comment]
Hi @raspberri05!

We appreciate your **PR**, but it would be nice if it can have also the required fields (description, usage and maybe an example). 

On the other hand, we did some changes in the code history and it is needed a new PR. So, please create a new branch with the latest changes of beta.

**Comment by danielalvarezm** [comment]
Hello guys! I want to do this issue, if there is no update

**Comment by Marius9595** [comment]
Hi @danielalvarezm!

Nice, I think we could assign this task to you, I will see the PR you created :D

**Comment by shahzdvp** [comment]
i would like to work on this issue

**Comment by Marius9595** [comment]
Hi @shahzdvp :D 

Thank you for wanting to contribute 😄. Unfortunately, this issue is already assigned and it is in progress.
